controller_frequency: 2

TrajectoryPlannerROS:
  max_vel_x: 5.0 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 6.28319 #1.5

  min_in_place_vel_theta: 6.28319

  acc_lim_theta: 6.28319
  acc_lim_x: 3.0
  acc_lim_y: 3.0

  sim_time: 5.0

  vx_samples: 10.0
  vtheta_samples: 10.0

  pdist_scale: 0.1 #0.6
  gdist_scale: 0.1 #0.8
  occdist_scale: 0.1

  holonomic_robot: false
