global_costmap:
  global_frame: map
  robot_base_frame: robot_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  width: 15.0
  height: 15.0
  resolution: 0.01

  # amcl calls this service to retrieve the map that is used for laser-based 	
  # localization
  static_map: true

  # Global map centered on robot?  No, it is centered on the static map.
  rolling_window: false

